### PR TITLE
Auto Provisioning of Dashboards and Postgres Metrics

### PR DESCRIPTION
**Pull request by runewake2**
I need to clean this up still and write a better description but a quick pass at getting Postgres metrics and dashboard provisioning setup.

This dashboard will show total storage space usage by database.

### CODE REVIEW

**Comment by jenniferplusplus** [comment]
@runewake2 I just wanted to check if this is ready to review? It's a draft, so I was holding off.

**Comment by runewake2** [comment]
I think you could take a look, but it's definitely still a rough pass just to get things working still. Planning to take a deeper look soon - idk if you'd want that rolled in here or split apart (I don't mind either way).

**Comment by jenniferplusplus** [comment]
Well, I fired it up. There's a dashboard and lots of PG metrics available, and it just works. So, seems good so far.

**Comment by jenniferplusplus** [comment]
This was completed in #189

**Pull request closed without merging**
